### ISSUE TITLE
Inconsistent license info

### ISSUE THREAD

**Issue by ryanmolden** [yaronn/xpath.js#15]
The package.json says this is MIT, xpath.js says it is Creative Commons Attribution-ShareAlike License.

**Comment by yaronn** [comment]
thanks, I've standardized on Creative Commons Attribution-ShareAlike which is the original license for this code.

**Comment by rmg** [comment]
@yaronn FYI, it looks like you forgot to publish a release after you fixed this. The license is still listed as `MIT` on npmjs.org.

**Comment by yaronn** [comment]
done!
