### ISSUE TITLE
Error when defaultnamespace

### ISSUE THREAD

**Issue by alexandrev** [yaronn/xpath.js#16]
I'm using your library as a base from my xpath-tool, that you can watch here: https://github.com/alexandrev/xpath-tool but I'm facing an issue when you have a default namespace. I'm adding the namespace using the useNamespace function but with no prefix ("") as it has been stored on the nsMap from xmldom when it parses the document. So then when I write the xpath expression I mean to use default namespace but it doesn't seem that is working. A real example:

XML Document
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Project xmlns="http://schemas.microsoft.com/project">
    <SaveVersion>9</SaveVersion>
    <Name>DndTesting</Name>
    <Title>DndTesting</Title>
    <Manager></Manager>
    <ScheduleFromStart>1</ScheduleFromStart>
    <StartDate>2016-01-15T08:00:00</StartDate>
    <FinishDate>2016-10-21T17:00:00</FinishDate>
    <FYStartDate>1</FYStartDate>
    <CriticalSlackLimit>0</CriticalSlackLimit>
....
```
The namespace I add using usenamespace functions it is hte following JSON: 
```{"": "http://schemas.microsoft.com/project"}```

But after all that set up the xpath expression //Project doesn't return anything!

Please, take a look and if you need more help or info from my side, let me know!

**Comment by yaronn** [comment]
Hi @alexandrev, I don't actively maintain this project anymore. I'm not sure I fully understand the issue - what is the useNamespace api? I'm not sure if it's legal to define a default namespace like that externally - do other xpath engines work that way? you can always do something like that:

    //*[local-name(.)='Project']

**Comment by alexandrev** [comment]
hi @yaronn. First of all, sorry for bothering you since the project is not been active maintained. I'm using a fork of your API and I also open the issue on their repo: https://github.com/goto100/xpath/issues/36. The API have a method name xpath.useNamespace you can use to add the namespaces you want to use inside your XPATH expressions:

```
exports.useNamespaces = function(mappings) {
	var resolver = {
		mappings: mappings || {},
		lookupNamespaceURI: function(prefix) {
			return this.mappings[prefix];
		}
	};

	return function(e, doc, single) {
		return exports.selectWithResolver(e, doc, resolver, single);
	};
};
```

I've been seen now that this function is not on your version, so you probably doesn't have anything to do with the issue. So I'm going to close it. And once again, thank you very much for your help.
