### ISSUE TITLE
CC-SA License Should not be used with software

### ISSUE THREAD

**Issue by raijinsetsu** [yaronn/xpath.js#20]
We are currently going through a license review and the CC-SA-2.0 license, which is used by this module and is an indirect dependency, was found.

This is problematic because the license is specific to artistic endeavors: music, art, movies, etc. and our legal team is having difficulty making heads or tails of how this applies to our indirect usage of the module. The Creative Commons site itself says that it should not be used for software.

Ultimately, it would be appreciated if a different license were selected. Changing out this module in lieu of another is not easy because we would need to fork a half-dozen modules to get to this module.

At a minimum, an explanation of how the "derivative" or "collection" statements in the CC-SA-2.0 license could be applied to this piece of software. Our interpretation is that we fall into the "Collective Works" qualification because we are in no way modifying or augmenting the module but our legal department will not take our word and has required that we reach out to the software's maintainers.

**Comment by yaronn** [comment]
@heycam - are you ok with changing the license to mit?

**Comment by heycam** [comment]
Sorry for delay in responding.  I'm fine with relicensing my contributions under the MIT license.  (It was obviously a mistake to use CC for code in the first place.)  What I'm not sure about is the other contributions that were made earlier.  Unfortunately I can't seem to find copies of the earlier revisions to know exactly what the changes mentioned in the big comment at the top of `xpath.js` were.  We could make a judgement about whether the contributions (per their descriptions in the comment) are trivial enough to not require explicit relicensing commitments from the contributors, and make an attempt to contact those who did make substantive fixes.  Unfortunately I don't have the time to look at this, but @yaronn please feel free to, if you do.

**Comment by yaronn** [comment]
I think at this stage xml parsers are probably a commodity and it is safe to make this library under MIT. I have added a note on this to the README.

**Comment by asmundg** [comment]
The README and package.json are now out of sync. :)

**Comment by raijinsetsu** [comment]
@yaronn @heycam Do you want me to submit a PR for this? Our legal department will not let us use this package or any package that relies on it until the license is updated throughout the documentation.

Thanks

**Comment by yaronn** [comment]
Yes would gladly accept a PR.

**Comment by jeffwilcox** [comment]
We'd love to use the MIT-licensed version of this `npm` package, any chance an updated version will be pushed to npmjs soon?

**Comment by jeffwilcox** [comment]
@yaronn proposing a PR with a version `1.1.0` to go along with the relicensed package! https://github.com/yaronn/xpath.js/pull/22

**Comment by jabeerni** [comment]
Just wondering if there is a plan to integrate this change and up the version number. Running into that same issue with legal and need to have this resolved before shipping. Thanks.

**Comment by yaronn** [comment]
done, sorry for the delay
